image: python:3.9

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - static_analysis
  - test

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r ci_requirements.txt

pylint:
  stage: static_analysis
  allow-failure: true
  script:
  - pip install pylint
  - pylint src

unit_test:
  stage: test
  script:
  - pip install pytest
  - pytest