image: python:3.9

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - static_analysis
  - test

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r ci_requirements.txt

pylint:
  stage: static_analysis
  allow_failure: true
  before_script:
  - mkdir -p public/badges public/lint
  - echo undefinded > public/badges/$CI_JOB_NAME.score
  - pip install pylint pylint-gitlab
  script:
  - pylint --exit-zero --output-format=text src | tee /tmp/pylint.txt
  - sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' /tmp/pylint.txt > public/badges/$CI_JOB_NAME.score
  - pylint --exit-zero --output-format=pylint_gitlab.GitlabCodeClimateReporter src > codeclimate.json
  - pylint --exit-zero --output-format=pylint_gitlab.GitlabPagesHtmlReporter src > public/lint/index.html
  after_script:
  - anybadge --overwrite --label $CI_JOB_NAME --value=$(cat public/badges/$CI_JOB_NAME.score) --file=public/badges/$CI_JOB_NAME.svg 4=red 6=orange 8=yellow 10=green
  - |
    echo "Your score is: $(cat public/badges/$CI_JOB_NAME.score)"
  artifacts:
    paths:
    - public
    reports:
      codequality: codeclimate.json

unit_test:
  stage: test
  script:
  - pip install pytest
  - pytest