# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-docstring-first
    -   id: check-yaml
        args: ['--unsafe']
    -   id: check-json
    -   id: debug-statements
    -   id: check-ast
    -   id: mixed-line-ending
        args: ['--fix=no']
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: name-tests-test
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
-   repo: https://github.com/akaihola/darker
    rev: 1.3.0
    hooks:
    -   id: darker
        args: [-i]
        additional_dependencies: [isort]
