name: Static Code Analysis

on:
  pull_request:
  push:
    branches: ["main"]

permissions: {}

jobs:
  flake8:
    strategy:
      matrix:
        python-version: ["3.11"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Install package
        run: python -m pip install -e .
      - name: Analysing the code with flake8
        run: |
          flake8 --color=never --tee --output-file=flake8-output src
      - name: Upload flake8 output
        uses: actions/upload-artifact@v3
        with:
          name: flake8-output
          path: flake8-output
        if: always()

  mypy:
    strategy:
      matrix:
        python-version: ["3.11"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Install package
        run: python -m pip install -e .
      - name: Analysing the code with mypy
        run: |
          mypy src
