name: Python

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest pytest-cases pytest-mock pytest-qt
      - name: Install package
        run: python -m pip install -e .
      - name: Test with pytest
        run: |
          coverage run -m pytest --junit-xml=test-results.xml src/tests
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: test-results.xml
        if: ${{ always() }}
